@AirsoftAPI_HostAddress = https://localhost:7060

POST {{AirsoftAPI_HostAddress}}/api/user
Content-Type: application/json

{
  "name" : "Admin", 
  "email" : "admin@gmail.com",
  "password" : "admin123"
}

###

GET {{AirsoftAPI_HostAddress}}/api/user

###





GET {{AirsoftAPI_HostAddress}}/api/user/login/admin@gmail.com/admin123

###
